site_name: Pano2VR
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Adding Images: adding-images.md
  - Adding Videos: adding-videos.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - glightbox